[package]
name = "gpu"
version = "1.0.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
render = { path = "../render" }
vir = { git = "https://github.com/exdal/vir.git", package = "vir" }
ash = "0.38.0"
raw-window-handle = "0.6.0"
dear-imgui-rs = "=0.17.0"

[build-dependencies]
shader-slang = "0.1.0"
