[package]
name = "codegen"
version = "1.1.0"
edition = "2024"

[dependencies]
rustc-hash = "2"
core = { path = "../core" }
ir = { path = "../ir" }
objtree = { path = "../objtree" }
prelude = { path = "../../prelude" }

[dev-dependencies]
ast = { path = "../ast" }
lexer = { path = "../lexer" }
sema = { path = "../sema" }
