[package]
name = "edit"
version = "1.0.0"
edition = "2024"

[[bin]]
name = "dmede"
path = "src/main.rs"

[dependencies]
core = { path = "../core" }
dmm = { path = "../dmm" }
dmi = { path = "../dmi" }
editor = { path = "../editor" }
render = { path = "../render" }
gpu = { path = "../gpu" }
objtree = { path = "../objtree" }
winit = "0.30.12"
raw-window-handle = "0.6.0"
dear-imgui-rs = "=0.17.0"
dear-imgui-winit = "=0.17.0"
