[package]
name = "editor"
version = "1.9.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "rmde"
path = "src/main.rs"

[dependencies]
bitflags = "2"
core = { path = "../core" }
defines = { path = "../defines" }
preprocessor = { path = "../preprocessor" }
ast = { path = "../ast" }
sema = { path = "../sema" }
objtree = { path = "../objtree" }
ir = { path = "../ir" }
codegen = { path = "../codegen" }
vm = { path = "../vm" }
dmm = { path = "../dmm" }
dmi = { path = "../dmi" }
net = { path = "../net" }
render = { path = "../render" }
winit = "0.30.12"
raw-window-handle = "0.6.0"
dear-imgui-rs = { version = "=0.17.0", features = ["serde", "multi-viewport"] }
dear-imgui-winit = { version = "=0.17.0", features = ["multi-viewport"] }
serde = { version = "1", features = ["derive"] }
toml = "1"
rfd = "0.17.2"
png = "0.18"
ring = "0.17"
log = "0.4"
shlex = "1.3"
semver = "1"
ureq = { version = "3", features = ["json"] }
gix = { version = "0.87.1", default-features = false, features = ["attributes", "index", "revision", "max-performance-safe", "sha1"] }
jiff = "0.2"
arboard = { version = "3.6.1", features = ["wayland-data-control"] }
fontdb = "0.24.0"
