[package]
name = "editor"
version = "1.6.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "rmde"
path = "src/main.rs"

[dependencies]
core = { path = "../core" }
preprocessor = { path = "../preprocessor" }
ast = { path = "../ast" }
sema = { path = "../sema" }
objtree = { path = "../objtree" }
ir = { path = "../ir" }
codegen = { path = "../codegen" }
vm = { path = "../vm" }
dmm = { path = "../dmm" }
dmi = { path = "../dmi" }
render = { path = "../render" }
winit = "0.30.12"
raw-window-handle = "0.6.0"
dear-imgui-rs = { version = "=0.17.0", features = ["serde"] }
dear-imgui-winit = "=0.17.0"
serde = { version = "1", features = ["derive"] }
toml = "1"
rfd = "0.17.2"
log = "0.4"
shlex = "1.3"
