module spec;

[[vk::constant_id(0)]] public const bool SPRITE_INDIRECT = false;
[[vk::constant_id(1)]] public const bool SPRITE_WRITES_ID = false;
[[vk::constant_id(2)]] public const bool SPRITE_EDGE_ONLY = false;
[[vk::constant_id(3)]] public const bool SHOW_AREAS = false;
[[vk::constant_id(4)]] public const bool SHOW_AREA_OUTLINES = true;

[[vk::constant_id(10)]] public const bool HIGHLIGHT_TINT = false;
[[vk::constant_id(11)]] public const bool DELETE_MODE = false;
