[package]
name = "viewer"
version = "1.6.0"
edition = "2024"

[[bin]]
name = "rmdv"
path = "src/main.rs"

[dependencies]
core = { path = "../core" }
dmm = { path = "../dmm" }
dmi = { path = "../dmi" }
editor = { path = "../editor" }
render = { path = "../render" }
winit = "0.30.12"
raw-window-handle = "0.6.0"
