pub const VERSION_SOURCE: &str = include_str!(concat!(env!("OUT_DIR"), "/version.dm"));
pub const CORE_SOURCE: &str = include_str!("../core.dm");
pub const STDDEF_SOURCE: &str = include_str!("../stddef.dm");
pub const STDDEF_EXT_SOURCE: &str = include_str!("../stddef_ext.dm");
pub const DEMIR_SOURCE: &str = include_str!("../demir.dm");
pub const IMGUI_SOURCE: &str = include_str!("../imgui.dm");

include!(concat!(env!("OUT_DIR"), "/intrinsic.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_intrinsics_preserve_the_declared_abi() {
        assert_eq!(Intrinsic::try_from(100).unwrap(), Intrinsic::WorldNew);
        assert_eq!(Intrinsic::try_from(401).unwrap(), Intrinsic::Call);
        assert_eq!(Intrinsic::try_from(721).unwrap(), Intrinsic::DemirNodeGroup);
        assert_eq!(Intrinsic::try_from(722).unwrap(), Intrinsic::ImguiMousePopup);
        assert_eq!(Intrinsic::try_from(725).unwrap(), Intrinsic::ImguiEndPopup);
        assert_eq!(Intrinsic::try_from(1100).unwrap(), Intrinsic::ListAdd);
        assert!(Intrinsic::try_from(u16::MAX).is_err());
    }

    #[test]
    fn version_defines_match_the_tracked_stddef() {
        let tracked = include_str!("../BYOND_VERSION").trim();
        let (version, build) = tracked.split_once('.').unwrap();

        assert_eq!(
            VERSION_SOURCE,
            format!("#define DM_VERSION {version}\n#define DM_BUILD {build}\n")
        );
        assert!(
            STDDEF_SOURCE
                .lines()
                .take(5)
                .any(|line| line.trim() == format!("Version {tracked}")),
            "stddef.dm was generated by a different BYOND than BYOND_VERSION names"
        );
    }

    #[test]
    fn core_owns_the_required_root_types() {
        assert!(CORE_SOURCE.contains("/datum"));
        assert!(CORE_SOURCE.contains("/list"));
        assert!(CORE_SOURCE.contains("/alist"));
        for source in [STDDEF_EXT_SOURCE, DEMIR_SOURCE] {
            assert!(!source.contains("\n/datum\n"));
            assert!(!source.contains("\n/list\n"));
            assert!(!source.contains("\n/alist\n"));
        }
    }

    /// Keep BYOND declarations separate from the appearance-baking declarations.
    #[test]
    fn the_prelude_split_keeps_byond_and_demir_apart() {
        assert!(STDDEF_EXT_SOURCE.contains("\n/atom\n"));
        assert!(STDDEF_EXT_SOURCE.contains("\n/image\n"));
        assert!(STDDEF_EXT_SOURCE.contains("\n/world\n"));
        // Each implemented procedure owns its `set __demir_intrin` ABI marker.
        // The appearance schema and profile panel do not use intrinsic markers.
        assert!(!STDDEF_EXT_SOURCE.contains("demir_light"));
        assert!(!STDDEF_EXT_SOURCE.contains("demir_emissive"));
        assert!(!STDDEF_EXT_SOURCE.contains("demir_overlay"));
        assert!(!STDDEF_EXT_SOURCE.contains("/datum/demir"));
        assert!(!STDDEF_EXT_SOURCE.contains("imgui_"));

        assert!(DEMIR_SOURCE.contains("#define __DEMIR__"));
        assert!(DEMIR_SOURCE.contains("\n/datum/demir\n"));
        assert!(DEMIR_SOURCE.contains("demir_light_range"));
        // demir.dm reopens /atom for lighting fields. stddef_ext.dm owns the base declaration.
        assert!(!DEMIR_SOURCE.contains("parent_type = /datum"));
        assert!(!DEMIR_SOURCE.contains("/client"));
        assert!(!DEMIR_SOURCE.contains("/savefile"));
        assert!(!DEMIR_SOURCE.contains("/proc/imgui_"));

        assert!(IMGUI_SOURCE.contains("/proc/imgui_begin"));
        assert!(!IMGUI_SOURCE.contains("/datum/demir"));
    }
}
