pub const VERSION_SOURCE: &str = include_str!(concat!(env!("OUT_DIR"), "/version.dm"));
pub const CORE_SOURCE: &str = include_str!("../core.dm");
pub const STDDEF_SOURCE: &str = include_str!("../stddef.dm");
pub const DEMIR_SOURCE: &str = include_str!("../demir.dm");

include!(concat!(env!("OUT_DIR"), "/intrinsic.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_intrinsics_preserve_the_declared_abi() {
        assert_eq!(Intrinsic::try_from(100).unwrap(), Intrinsic::WorldNew);
        assert_eq!(Intrinsic::try_from(401).unwrap(), Intrinsic::Call);
        assert_eq!(Intrinsic::try_from(1100).unwrap(), Intrinsic::ListAdd);
        assert!(Intrinsic::try_from(u16::MAX).is_err());
    }

    #[test]
    fn version_defines_match_the_tracked_stddef() {
        let tracked = include_str!("../BYOND_VERSION").trim();
        let (version, build) = tracked.split_once('.').unwrap();

        assert_eq!(
            VERSION_SOURCE,
            format!("#define DM_VERSION {version}\n#define DM_BUILD {build}\n")
        );
        assert!(
            STDDEF_SOURCE
                .lines()
                .take(5)
                .any(|line| line.trim() == format!("Version {tracked}")),
            "stddef.dm was generated by a different BYOND than BYOND_VERSION names"
        );
    }

    #[test]
    fn core_owns_the_required_root_types() {
        assert!(CORE_SOURCE.contains("/datum"));
        assert!(CORE_SOURCE.contains("/list"));
        assert!(CORE_SOURCE.contains("/alist"));
        assert!(!DEMIR_SOURCE.contains("\n/datum\n"));
        assert!(!DEMIR_SOURCE.contains("\n/list\n"));
        assert!(!DEMIR_SOURCE.contains("\n/alist\n"));
    }
}
